CREATE TABLE PRODUCTOS (
    ID_PRODUCTO VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
	PRECIO DECIMAL(10,2) NOT NULL,
	MODELO VARCHAR(10) NOT NULL
);

ALTER TABLE PRODUCTOS ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO);

